import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import SessionProvider from "@/app/utils/SessionProvider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className= {inter.className}  >
      <SessionProvider session={session}>
          <main className="max-w-6xl mx-auto  p-4">
            
              <Header/>
              {children}
              <footer className=" border-t p-8 text-center text-gray-500 mt-16 ">
                          &copy; 2024 All right reserved
              </footer>
           
        
        </main>
        </SessionProvider>
      </body>
    </html> 
  );
}

{/* <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            <Header/>
            {children}
          </div>
        </SessionProvider>
      </body>
    </html> */}



// const roboto = Roboto({ subsets: ["latin"] , weight: ['400','500','700'] });

//  <html lang="en">
//       <body className= {roboto.className }  >
//           <main className="max-w-6xl mx-auto  p-4">
            
//               <Header/>
//               {children}
//               <footer className=" border-t p-8 text-center text-gray-500 mt-16 ">
//                           &copy; 2024 All right reserved
//               </footer>
           
        
//         </main>
//       </body>
//     </html> 